#Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

#1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

#It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised;
                # what is the value of D?
def pentagonal_number():
    list = []
    for i in range(1, 4000):
        list.append(int(i*(3*i-1) / 2))
    j = 1
    while True:
        for k in list:
            if k + list[j] in list:
                if list[j] - k in list:
                    return list[j] - k, list[j], k
        j += 1



print(pentagonal_number())