#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

#Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
#Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
#Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
#It can be verified that T285 = P165 = H143 = 40755.

#Find the next triangle number that is also pentagonal and hexagonal.

def tri():
    list = []
    i = 286
    while i < 100000:
        t = i * (i+1)/2
        list.append(int(t))
        i += 1
    return list

def pent():
    j = 166
    list = []
    while j < 100000:
        p = j * (3*j - 1) / 2
        list.append(int(p))
        j += 1
    return list

def hex():
    k = 144
    list = []
    while k < 100000:
        h = k * (2*k -1)
        list.append(int(h))
        k += 1
    return list

def common(a, b, c):
    for i in a:
        if i in b:
            if i in c:
                return i



print(common(tri(), pent(), hex()))
